// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package vault is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	EncryptedMessage
*/
package vault

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EncryptedMessage struct {
	Backend    string `protobuf:"bytes,1,opt,name=Backend" json:"Backend,omitempty"`
	Key        string `protobuf:"bytes,2,opt,name=Key" json:"Key,omitempty"`
	CipherText string `protobuf:"bytes,3,opt,name=CipherText" json:"CipherText,omitempty"`
}

func (m *EncryptedMessage) Reset()                    { *m = EncryptedMessage{} }
func (m *EncryptedMessage) String() string            { return proto.CompactTextString(m) }
func (*EncryptedMessage) ProtoMessage()               {}
func (*EncryptedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EncryptedMessage) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *EncryptedMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EncryptedMessage) GetCipherText() string {
	if m != nil {
		return m.CipherText
	}
	return ""
}

func init() {
	proto.RegisterType((*EncryptedMessage)(nil), "EncryptedMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x8a, 0xe3, 0x12, 0x70, 0xcd, 0x4b,
	0x2e, 0xaa, 0x2c, 0x28, 0x49, 0x4d, 0xf1, 0x85, 0xc8, 0x08, 0x49, 0x70, 0xb1, 0x3b, 0x25, 0x26,
	0x67, 0xa7, 0xe6, 0xa5, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x42, 0x02, 0x5c,
	0xcc, 0xde, 0xa9, 0x95, 0x12, 0x4c, 0x60, 0x51, 0x10, 0x53, 0x48, 0x8e, 0x8b, 0xcb, 0x39, 0xb3,
	0x20, 0x23, 0xb5, 0x28, 0x24, 0xb5, 0xa2, 0x44, 0x82, 0x19, 0x2c, 0x81, 0x24, 0xe2, 0xc4, 0x1e,
	0xc5, 0x5a, 0x96, 0x58, 0x9a, 0x53, 0x92, 0xc4, 0x06, 0xb6, 0xcf, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x57, 0xd3, 0xad, 0x2c, 0x80, 0x00, 0x00, 0x00,
}
